<a href="https://colab.research.google.com/github/mnindrazaka/StatistikaTerapan/blob/implementasi-random-sampling/Implementasi_Random_Sampling_Menggunakan_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Implementasi Random Sampling Menggunakan Python

## 1. Random Sampling Pada List

### 1.1 Tanpa Redudansi

In [3]:
import random

data = [1, 2, 3, 4, 5]
print("3 data terpilih untuk dijadikan sampel adalah : ", random.sample(data, k=3))

3 data terpilih untuk dijadikan sampel adalah :  [5, 1, 3]


### 1.2 Dengan Redudansi

In [9]:
import random

data = [1, 2, 3, 4, 5]
print("3 data terpilih untuk dijadikan sampel adalah : ", random.choices(data, k=3))

3 data terpilih untuk dijadikan sampel adalah :  [2, 2, 2]


### 1.3 Nested List

In [16]:
import random
import numpy

data = numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
])

randomData = numpy.random.randint(6, size=3)

print("3 data terpilih untuk dijadikan sampel adalah : ")
for i in randomData:
  print(data[i])

3 data terpilih untuk dijadikan sampel adalah : 
[13 14 15]
[7 8 9]
[16 17 18]


## 2. Random Sampling Pada Set

### 2.1 Tanpa Redudansi

In [17]:
import random

data = {1, 2, 3, 4, 5}
print("3 data terpilih untuk dijadikan sampel adalah : ", random.sample(data, k=3))

3 data terpilih untuk dijadikan sampel adalah :  [2, 3, 5]


## 3. Random Sampling Pada Dictionary

### 3.1 Tanpa Redudansi

In [22]:
import random

data = {
    "aka": 1,
    "fany": 2,
    "berlian": 3,
    "brilian": 4,
    "dirga": 5
}
print("3 data terpilih untuk dijadikan sampel adalah : ", random.sample(data.items(), k=3))

3 data terpilih untuk dijadikan sampel adalah :  [('brilian', 4), ('dirga', 5), ('aka', 1)]
